##
## -------------------------
## |   M E D I A B O X     |
## -------------------------
##
##
## Configuration variables for this file are taken from the .env file
##
## Have docker-compose.yml and .env in the same directory to launch the stack

version: '3.8'

services:

  # ----------------------------------------
  # DELUGEVPN
  # ----------------------------------------
  arch-delugevpn:
    image: binhex/arch-delugevpn:2.1.1-3-07
    container_name: delugevpn
    restart: unless-stopped
    network_mode: "bridge"
    ports:
        - '${IP_ADDRESS}:8112:8112'
        - '${IP_ADDRESS}:8118:8118'
        - '${IP_ADDRESS}:58846:58846'
        - '${IP_ADDRESS}:58946:58946'
    cap_add:
        - NET_ADMIN
    environment:
        - VPN_ENABLED=yes
        - VPN_USER=${PIAUNAME}
        - VPN_PASS=${PIAPASS}
        - VPN_REMOTE=${VPN_REMOTE}
        - VPN_PORT=1198
        - VPN_PROTOCOL=udp
        - VPN_DEVICE_TYPE=tun
        - VPN_PROV=pia
        - STRONG_CERTS=no
        - ENABLE_PRIVOXY=yes
        - STRICT_PORT_FORWARD=yes
        - LAN_NETWORK=${CIDR_ADDRESS}
        - NAME_SERVERS=84.200.69.80,37.235.1.174,1.1.1.1,37.235.1.177,84.200.70.40,1.0.0.1
        - DEBUG=false
        - PUID=${PUID}
        - PGID=${PGID}
    volumes:
        - '${DLDIR}:/data'
        - './delugevpn/config:/config'
        - '/etc/localtime:/etc/localtime:ro'

  # ----------------------------------------
  # FLARESOLVERR
  # ----------------------------------------
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    restart: unless-stopped
    network_mode: "bridge"
    environment:
        - LOG_LEVEL=${LOG_LEVEL:-info}
        - LOG_HTML=${LOG_HTML:-false}
        - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
    ports:
        - '${IP_ADDRESS}:8191:8191'
    volumes:
        - /etc/localtime:/etc/localtime:ro
        - ./flaresolverr:/storage

  # ----------------------------------------
  # HOMER
  # ----------------------------------------
  homer:
    image: b4bz/homer:latest
    container_name: homer
    restart: unless-stopped
    network_mode: "bridge"
    ports:
        - '${IP_ADDRESS}:80:8080'
    environment:
        - UID=${PUID}
        - GID=${PGID}
    volumes:
        - './homer:/www/assets'

  # ----------------------------------------
  # JACKETT
  # ----------------------------------------
  jackett:
    image: lscr.io/linuxserver/jackett
    container_name: jackett
    restart: unless-stopped
    network_mode: "bridge"
    ports:
        - '${IP_ADDRESS}:9117:9117'
    environment:
        - PUID=${PUID}
        - PGID=${PGID}
    volumes:
        - './jackett:/config'
        - '${DLDIR}/completed:/downloads'
        - '/etc/localtime:/etc/localtime:ro'

  # ----------------------------------------
  # LIDARR
  # ----------------------------------------
  lidarr:
    image: lscr.io/linuxserver/lidarr
    container_name: lidarr
    restart: unless-stopped
    network_mode: "bridge"
    ports:
        - '${IP_ADDRESS}:8686:8686'
    environment:
        - PUID=${PUID}
        - PGID=${PGID}
    volumes:
        - './lidarr:/config'
        - '${DLDIR}/completed:/data/completed'
        - '${MUSICDIR}:/music'
        - '/etc/localtime:/etc/localtime:ro'

  # ----------------------------------------
  # MUXIMUX
  # ----------------------------------------
  muximux:
    image: lscr.io/linuxserver/muximux
    container_name: muximux
    restart: unless-stopped
    network_mode: "bridge"
    ports:
        - '${IP_ADDRESS}:8080:80'
    environment:
        - PUID=${PUID}
        - PGID=${PGID}
    volumes:
        - './muximux:/config'
        - '/etc/localtime:/etc/localtime:ro'

  # ----------------------------------------
  # PLEX
  # ----------------------------------------
  plex:
    container_name: plex
    image: plexinc/pms-docker:${PMSTAG}
#    image: lscr.io/linuxserver/plex:amd64-latest
    restart: unless-stopped
    network_mode: "bridge"
    ports:
        - '${IP_ADDRESS}:32400:32400/tcp'
        - '${IP_ADDRESS}:3005:3005/tcp'
        - '${IP_ADDRESS}:8324:8324/tcp'
        - '${IP_ADDRESS}:32469:32469/tcp'
        - '${IP_ADDRESS}:1900:1900/udp'
        - '${IP_ADDRESS}:32410:32410/udp'
        - '${IP_ADDRESS}:32412:32412/udp'
        - '${IP_ADDRESS}:32413:32413/udp'
        - '${IP_ADDRESS}:32414:32414/udp'
    environment:
        - PLEX_CLAIM=${PMSTOKEN}
        - ADVERTISE_IP=http://${IP_ADDRESS}:32400/
        - ALLOWED_NETWORKS=${CIDR_ADDRESS}
 #       - PUID=${PUID}
 #       - PGID=${PGID}
 #       - VERSION=latest
        - PUID=1000
        - PGID=1000
        - VERSION=docker
    hostname: ${HOSTNAME}
    volumes:
        - './plex:/config'
        - './plex/transcode:/transcode'
        - '${MISCDIR}:/data/misc'
        - '${MOVIEDIR}:/data/movies'
        - '${MUSICDIR}:/data/music'
        - '${TVDIR}:/data/tvshows'
        - '/etc/localtime:/etc/localtime:ro'
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]
            
  # ----------------------------------------
  # PORTAINER
  # ----------------------------------------
  portainer:
    image: portainer/portainer-ce:2.18.4
    container_name: portainer
    restart: unless-stopped
    network_mode: "bridge"
    ports:
        - '${IP_ADDRESS}:8000:8000'
        - '${IP_ADDRESS}:9443:9443'      
    environment:
        - PUID=${PUID}
        - PGID=${PGID}
    volumes:
        - './portainer:/data'
        - '/var/run/docker.sock:/var/run/docker.sock'
        - '/etc/localtime:/etc/localtime:ro'
    command: -H unix:///var/run/docker.sock

  # ----------------------------------------
  # RADARR
  # ----------------------------------------
  radarr:
    image: lscr.io/linuxserver/radarr:5.6.0.8846-ls220
    container_name: radarr
    restart: unless-stopped
    network_mode: "bridge"
    ports:
        - '${IP_ADDRESS}:7878:7878'
    environment:
        - PUID=${PUID}
        - PGID=${PGID}
    volumes:
        - './radarr:/config'
        - '${DLDIR}/completed:/data/completed'
        - '${MOVIEDIR}:/movies'
        - '/etc/localtime:/etc/localtime:ro'

  # ----------------------------------------
  # SONARR
  # ----------------------------------------
  sonarr:
    image: lscr.io/linuxserver/sonarr
    container_name: sonarr
    restart: unless-stopped
    network_mode: "bridge"
    ports:
        - '${IP_ADDRESS}:8989:8989'
    environment:
        - PUID=${PUID}
        - PGID=${PGID}
        - TZ=${TZ}
    volumes:
        - './sonarr:/config'
        - '${DLDIR}/completed:/data/completed'
        - '${TVDIR}:/tv'
        - '/etc/localtime:/etc/localtime:ro'

  # ----------------------------------------
  # TAUTULLI
  # ----------------------------------------
  tautulli:
    image: tautulli/tautulli
    container_name: tautulli
    restart: unless-stopped
    network_mode: "bridge"
    ports:
        - '${IP_ADDRESS}:8181:8181'
    environment:
        - PUID=${PUID}
        - PGID=${PGID}
        - TZ=${TZ}
    volumes:
        - './tautulli:/config'
        - './plex/Library/Application Support/Plex Media Server/Logs:/logs:ro'
    depends_on:
        - plex

  # ----------------------------------------
  # WATCHTOWER
  # ----------------------------------------
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: unless-stopped
    network_mode: "bridge"
    hostname: '${HOSTNAME}'
    environment:
        - WATCHTOWER_CLEANUP=true
        - WATCHTOWER_SCHEDULE=0 0 */4 * * *
        - WATCHTOWER_INCLUDE_STOPPED=true
        - TZ=${TZ}
    volumes:
        - '/var/run/docker.sock:/var/run/docker.sock'

